extends RefCounted
class_name CoreTuning

const BASE_VILLAGER_HEALTH: int = 5

const HUNGER_FULL: int = 100
const HUNGER_EAT_THRESHOLD: int = 40

const BASE_SPEED: int = 100
const MIN_BASE_SPEED: int = 90
const MAX_BASE_SPEED: int = 100
const MIN_SPEED: int = 10

const DEFAULT_SKILL_CAP: int = 10

const BASE_BELONGING_SLOTS: int = 1

const DEFAULT_ASSIGNED_WORK_RADIUS: int = 3

const STARTING_POPULATION: int = 3
const POPULATION_GROWTH_INTERVAL: float = 120.0
const POPULATION_GROWTH_CHANCE: float = 0.45

const VILLAGER_MOVE_INTERVAL: float = 0.18
const DEFAULT_HARVEST_DURATION: float = 1.0

const SKILL_HARVEST_SPEED_BONUS_PER_LEVEL: float = 0.02

# Core hunting timing.
const HUNT_BASE_DURATION: float = 5.0
const HUNT_REQUIRED_HUNTER_DURATION_BONUS: float = 1.0

const HUNT_NORMAL_DURATION_MODIFIER: float = 0.0
const HUNT_DANGEROUS_DURATION_MODIFIER: float = 4.0
const HUNT_HIGH_DANGER_DURATION_MODIFIER: float = 8.0
const HUNT_EXTREME_DANGER_DURATION_MODIFIER: float = 14.0

const HUNTING_SKILL_DURATION_REDUCTION_PER_LEVEL: float = 1.0
const HUNT_MIN_DURATION: float = 2.0

# Core dangerous hunting tick tuning.
const HUNT_DANGER_TICK_INTERVAL: float = 10.0
const HUNT_EVADE_INJURY_CHANCE_REDUCTION_PER_LEVEL: float = 0.02
const HUNT_MIN_INJURY_CHANCE: float = 0.02
const HUNT_MIN_DAMAGE: int = 1
const HUNT_NO_REPLACEMENT_TIME_PENALTY: float = 10.0
